// Turns an SVG the extension built into a transparent PNG.
// This script was generated by Claude AI.

(function () {
  const vscode = acquireVsCodeApi();

  function fail(message) {
    vscode.postMessage({ type: "error", message: message });
  }

  function draw(request) {
    const img = new Image();

    img.onload = function () {
      const canvas = document.createElement("canvas");
      canvas.width = request.width;
      canvas.height = request.height;
      const ctx = canvas.getContext("2d");
      if (ctx === null) {
        fail("this view has no 2D canvas");
        return;
      }
      // The ground is never filled and alpha is the 2D context default, so the canvas
      // starts transparent and toDataURL writes RGBA. The SVG references nothing external
      // - one inside an <img> cannot load anything at all - so the canvas is never
      // tainted and toDataURL is allowed to read it back.
      ctx.drawImage(img, 0, 0, request.width, request.height);
      vscode.postMessage({
        type: "png",
        base64: canvas.toDataURL("image/png").split(",")[1],
      });
    };

    // Fires when the markup is not well-formed XML - a stray & in a parameter name, say.
    img.onerror = function () {
      fail("the generated SVG could not be decoded");
    };

    // A data: uri rather than a blob: url - the policy then only has to allow data:, and
    // there is no object url to revoke. Not base64 either: encodeURIComponent carries the
    // Greek letters through, which btoa (latin-1 only) would not.
    img.src = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(request.svg);
  }

  window.addEventListener("message", function (event) {
    if (event.data && event.data.type === "render") {
      try {
        draw(event.data);
      } catch (error) {
        fail(String(error));
      }
    }
  });

  // Says the script actually ran. Without it, a policy or resource-root mistake would be
  // indistinguishable from a rasterisation that simply failed.
  vscode.postMessage({ type: "ready" });
})();
