import * as path from "path";
import * as vscode from "vscode";
import { parseTable, Table } from "./table";

// Paths declared in a project file are relative to the project folder
export function resolveProjectPath(projectUri: vscode.Uri, target: string): vscode.Uri {
  return path.isAbsolute(target)
    ? vscode.Uri.file(target)
    : vscode.Uri.joinPath(projectUri, "..", target);
}

// Reads a file
export async function readText(uri: vscode.Uri): Promise<string | undefined> {
  try {
    return new TextDecoder().decode(await vscode.workspace.fs.readFile(uri));
  } catch {
    // File missing: the section will be hidden
    return undefined;
  }
}

export async function readTable(uri: vscode.Uri): Promise<Table | undefined> {
  const text = await readText(uri);
  return text === undefined ? undefined : parseTable(text);
}

// Check if a file exist
export async function exists(uri: vscode.Uri): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(uri);
    return true;
  } catch {
    return false;
  }
}

// .Internals and ModelBuilding are generated by MonolixSuite are ignored
const EXCLUDE = "**/{node_modules,.git,.Internals,ModelBuilding}/**";

// Scan every file matching `glob` to find mlx project files
export async function scanProjects(
  glob: string,
  identifies: (content: string) => boolean
): Promise<vscode.Uri[]> {
  const candidates = await vscode.workspace.findFiles(glob, EXCLUDE);
  const decoder = new TextDecoder();
  const projects: vscode.Uri[] = [];

  for (const uri of candidates) {
    try {
      const bytes = await vscode.workspace.fs.readFile(uri);
      if (identifies(decoder.decode(bytes))) {
        projects.push(uri);
      }
    } catch {
      // Ignore file deleted or unreadable
    }
  }

  return projects.sort((a, b) =>
    vscode.workspace.asRelativePath(a).localeCompare(vscode.workspace.asRelativePath(b))
  );
}
