/**
 * This code was generated by Claude AI
 */

import { randomUUID } from "crypto";
import * as vscode from "vscode";
import { Rendered } from "./svgTable";
import { revealPanel } from "./webview";

// Generous for a table of a few dozen rows. Past this the script is not coming back, and
// the cause is far more likely the policy or the resource root than a slow render.
const TIMEOUT = 10_000;

function page(webview: vscode.Webview, extensionUri: vscode.Uri): string {
  const nonce = randomUUID().replace(/-/g, "");
  const script = webview.asWebviewUri(
    vscode.Uri.joinPath(extensionUri, "webview", "rasterize.js")
  );
  // A nonce authorises the external script too, so neither 'unsafe-inline' nor an extra
  // source expression is needed. `img-src data:` is for the SVG the script hands to an
  // <img>; there is no style-src because the page has no stylesheet at all.
  const csp = `default-src 'none'; img-src data:; script-src 'nonce-${nonce}';`;
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="${csp}">
</head>
<body>
<script nonce="${nonce}" src="${script}"></script>
</body>
</html>`;
}

/**
 * Renders an SVG to PNG bytes with its transparency intact.
 */
export async function rasterize(
  extensionUri: vscode.Uri,
  rendered: Rendered,
  behind: string
): Promise<Uint8Array> {
  const panel = vscode.window.createWebviewPanel(
    "mlx-explorer.rasterize",
    "Rendering image…",
    { viewColumn: vscode.ViewColumn.Active, preserveFocus: true },
    {
      enableScripts: true,
      // Keeps the page alive once it drops behind the results tab.
      retainContextWhenHidden: true,
      // The script is the only thing this panel may reach.
      localResourceRoots: [vscode.Uri.joinPath(extensionUri, "webview")],
    }
  );

  try {
    panel.webview.html = page(panel.webview, extensionUri);
    revealPanel(behind);

    return await new Promise<Uint8Array>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error("timed out rendering the image")), TIMEOUT);
      const settle = (finish: () => void) => {
        clearTimeout(timer);
        finish();
      };

      // Fires when the user closes the transient tab mid-render.
      panel.onDidDispose(() => settle(() => reject(new Error("the rendering view was closed"))));

      panel.webview.onDidReceiveMessage((message) => {
        if (message?.type === "png") {
          settle(() => resolve(Buffer.from(String(message.base64), "base64")));
        } else if (message?.type === "error") {
          settle(() => reject(new Error(String(message.message))));
        } else if (message?.type === "ready") {
          // One panel per export, so there is exactly one render and nothing to correlate.
          panel.webview.postMessage({ type: "render", ...rendered });
        }
      });
    });
  } finally {
    panel.dispose();
  }
}
