/**
 * Renders a results table as a standalone SVG, on a transparent ground, in the "booktabs"
 * style of a published table: horizontal rules only, no zebra, no verticals, one ink.
 *
 * This code was generated by Claude AI.
 */

import { EMPTY_CELL, formatFixed, Formatted, formatSignificant } from "./table";
import { Label, parseSymbol } from "./symbols";

export type CellFormat =
  | { kind: "symbol" } // a parameter name: Greek base, subscript index
  | { kind: "text" }
  | { kind: "significant"; digits: number }
  | { kind: "fixed"; decimals: number };

export interface ExportColumn {
  header: string;
  format: CellFormat;
  /** Adjacent columns sharing a group get one spanning label and a rule above them. */
  group?: string;
}

export interface ExportTable {
  title: string;
  columns: ExportColumn[];
  /** Raw source strings, one per column - never the values already rounded for the page. */
  rows: string[][];
}

export interface SvgOptions {
  ink: "dark" | "light";
  scale: number;
}

// Ink, not "colour": the export is one solid tone on nothing, and the choice is only which
// way round it has to read on the slide.
const INK = { dark: "#1a1a1a", light: "#f2f2f2" };

// Helvetica, Arial and Liberation Sans all advance a digit by 0.556 em and are what
// PowerPoint actually resolves; DejaVu Sans, the Linux fallback, is 0.636 - which is the
// case the advance bound below has to cover.
const FONT = "Helvetica Neue, Helvetica, Arial, Liberation Sans, sans-serif";

const FS = 14; // base font size, in user units
const PAD = 1.4 * FS; // cell padding inside the rules
const GAP = 1.6 * FS; // gutter between columns - the shock absorber for a mis-guessed width
const MARGIN = 0.5 * FS; // outside the rules, so a stroke is never clipped
const ROW = 2.0 * FS;
const HEAD = 2.2 * FS;
const GROUP = 1.9 * FS;
const BASE = 0.35 * FS; // from a row's middle down to its text baseline
const THICK = 0.1 * FS;
const THIN = 0.05 * FS;

const SMALL = 0.72; // sub/superscript size, as a fraction of the base
const SUB_DY = 0.22; // downwards, in base font sizes
const SUP_DY = -0.38; // upwards

const MINUS = "−"; // U+2212 MINUS SIGN: a hyphen is too short to read as one

/**
 * Upper bound on one character's advance, in em. There is no way to measure text in the
 * extension host, so this is an approximation by construction. It only ever sets column
 * widths, and every cell is anchored rather than laid out: a generous guess pads a column,
 * a tight one would let two columns touch. It can never clip - the first column grows
 * rightwards from a fixed margin, the last leftwards from one.
 */
function advanceEm(ch: string): number {
  if ("il.,:;'|!".includes(ch)) {
    return 0.34;
  }
  if ("mwMW—×".includes(ch)) {
    return 0.95;
  }
  if (ch >= "A" && ch <= "Z") {
    return 0.75;
  }
  return 0.62; // digits, lowercase, Greek
}

function measureEm(text: string): number {
  let em = 0;
  for (const ch of text) {
    em += advanceEm(ch); // by code point, so ω σ × − each count once
  }
  return em;
}

// Text nodes need & < > escaped; attributes also need ". Everything else is valid XML.
function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// Short numbers keep the file readable and small; two decimals is well under a pixel here.
function n(value: number): string {
  return String(Math.round(value * 100) / 100);
}

/** One cell, ready to place: the inner markup of a <text>, and an upper bound on its width. */
interface Piece {
  markup: string;
  em: number;
}

function plain(text: string): Piece {
  return { markup: escapeXml(text), em: measureEm(text) };
}

function tspan(text: string, dy: number): string {
  return `<tspan font-size="${n(FS * SMALL)}" dy="${n(dy)}">${escapeXml(text)}</tspan>`;
}

/**
 * dy shifts rather than baseline-shift: dy is a plain positioning attribute every renderer
 * implements, baseline-shift is where slide importers diverge. dy accumulates, so each
 * shift is measured from wherever the previous one left the pen. Sub and superscript are
 * always last, so nothing ever has to return to the baseline.
 */
function labelPiece(label: Label): Piece {
  let markup = escapeXml(label.base);
  let em = measureEm(label.base);
  let dy = 0;

  for (const [part, target] of [
    [label.sup, SUP_DY],
    [label.sub, SUB_DY],
  ] as const) {
    if (part === undefined) {
      continue;
    }
    markup += tspan(part, target * FS - dy);
    em += SMALL * measureEm(part); // laid out after the base, not stacked over it
    dy = target * FS;
  }

  return { markup, em };
}

function numberPiece(value: Formatted): Piece {
  const text = value.text.replace(/^-/, MINUS);
  if (value.exponent === undefined) {
    return plain(text);
  }

  const lead = `${text} × 10`;
  const exponent = value.exponent.replace(/^-/, MINUS);
  return {
    markup: escapeXml(lead) + tspan(exponent, SUP_DY * FS),
    em: measureEm(lead) + SMALL * measureEm(exponent),
  };
}

function cellPiece(raw: string, format: CellFormat): Piece {
  switch (format.kind) {
    case "symbol":
      return labelPiece(parseSymbol(raw));
    case "significant":
      return numberPiece(formatSignificant(raw, format.digits));
    case "fixed":
      return plain(raw.trim() === "" ? EMPTY_CELL : formatFixed(raw, format.decimals));
    default:
      return plain(raw.trim() === "" ? EMPTY_CELL : raw);
  }
}

/** A run of adjacent columns carrying the same group label. */
interface Span {
  label: string;
  first: number;
  last: number;
}

function spans(columns: ExportColumn[]): Span[] {
  const found: Span[] = [];
  columns.forEach((column, index) => {
    if (column.group === undefined) {
      return;
    }
    const open = found[found.length - 1];
    if (open && open.label === column.group && open.last === index - 1) {
      open.last = index;
    } else {
      found.push({ label: column.group, first: index, last: index });
    }
  });
  return found;
}

function line(x1: number, x2: number, y: number, width: number, ink: string): string {
  return `<line x1="${n(x1)}" y1="${n(y)}" x2="${n(x2)}" y2="${n(y)}" ` +
    `stroke="${ink}" stroke-width="${n(width)}" fill="none" shape-rendering="crispEdges"/>`;
}

function textAt(x: number, y: number, anchor: string, piece: Piece, weight = ""): string {
  const bold = weight === "" ? "" : ` font-weight="${weight}"`;
  return `<text x="${n(x)}" y="${n(y)}" text-anchor="${anchor}"${bold}>${piece.markup}</text>`;
}

export interface Rendered {
  svg: string;
  width: number;
  height: number;
}

export function renderSvgTable(table: ExportTable, options: SvgOptions): Rendered {
  const ink = INK[options.ink];
  const headers = table.columns.map((column) => plain(column.header));
  const body = table.rows.map((row) =>
    table.columns.map((column, index) => cellPiece(row[index] ?? "", column.format))
  );

  // Widest of the header and every cell under it. The first column is a name and anchors
  // left; the rest are numbers and anchor right.
  const widths = table.columns.map((_, index) =>
    body.reduce((most, row) => Math.max(most, row[index].em), headers[index].em) * FS
  );

  // A group label wider than the columns it spans would run into its neighbours, so the
  // shortfall is shared out across them rather than left to overlap.
  const groups = spans(table.columns);
  for (const span of groups) {
    const count = span.last - span.first + 1;
    let covered = GAP * (count - 1);
    for (let i = span.first; i <= span.last; i++) {
      covered += widths[i];
    }
    const needed = measureEm(span.label) * FS;
    if (needed > covered) {
      const share = (needed - covered) / count;
      for (let i = span.first; i <= span.last; i++) {
        widths[i] += share;
      }
    }
  }

  const lefts: number[] = [];
  let x = PAD;
  for (const width of widths) {
    lefts.push(x);
    x += width + GAP;
  }
  const width = x - GAP + PAD;
  // Names read from the left; numbers read from the right, so their anchor is the column's
  // right edge and the digits line up whatever their length. Driven by the format rather
  // than the position, because a transposed table (the likelihood criteria) is all numbers.
  const rightAligned = (index: number) => {
    const kind = table.columns[index].format.kind;
    return kind !== "symbol" && kind !== "text";
  };
  const anchorX = (i: number) => (rightAligned(i) ? lefts[i] + widths[i] : lefts[i]);
  const anchor = (i: number) => (rightAligned(i) ? "end" : "start");

  const parts: string[] = [];
  let y = MARGIN;
  parts.push(line(0, width, y, THICK, ink));

  for (const span of groups) {
    const from = lefts[span.first];
    const to = lefts[span.last] + widths[span.last];
    parts.push(textAt((from + to) / 2, y + GROUP / 2 + BASE, "middle", plain(span.label), "600"));
    parts.push(line(from, to, y + GROUP - THIN * 2, THIN, ink));
  }
  if (groups.length > 0) {
    y += GROUP;
  }

  headers.forEach((piece, index) => {
    parts.push(textAt(anchorX(index), y + HEAD / 2 + BASE, anchor(index), piece, "600"));
  });
  y += HEAD;
  parts.push(line(0, width, y, THIN, ink));

  body.forEach((row, rowIndex) => {
    const baseline = y + rowIndex * ROW + ROW / 2 + BASE;
    row.forEach((piece, index) => {
      parts.push(textAt(anchorX(index), baseline, anchor(index), piece));
    });
  });
  y += body.length * ROW;
  parts.push(line(0, width, y, THICK, ink));

  const height = y + MARGIN;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${n(width * options.scale)}" ` +
    `height="${n(height * options.scale)}" viewBox="0 0 ${n(width)} ${n(height)}">\n` +
    `<g fill="${ink}" stroke="none" font-family="${escapeXml(FONT)}" font-size="${FS}">\n` +
    parts.join("\n") +
    `\n</g>\n</svg>\n`;

  return { svg, width: Math.ceil(width * options.scale), height: Math.ceil(height * options.scale) };
}
